version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./volume:/var/lib/postgresql
    environment:
      POSTGRES_DB: db_receitas
      POSTGRES_USER: medina
      POSTGRES_PASSWORD: 1378563
    networks:
      - development-network

  pgadmin:
    image: dpage/pgadmin4
    links:
      - postgres:postgres
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "receitas@receitas.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    depends_on:
      - postgres
    networks:
      - development-network

networks:
  development-network:
    driver: bridge
